# Generated by Django 4.1.2 on 2022-10-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('len_of_quote', models.IntegerField()),
                ('lower', models.IntegerField()),
                ('upper', models.IntegerField()),
                ('vowel', models.IntegerField()),
                ('consonants', models.IntegerField()),
            ],
        ),
    ]
