# Generated by Django 4.1.2 on 2022-11-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanye', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
